version: 2
jobs:
  build:
    working_directory: ~/ng-admin
    docker:
      - image: circleci/node:10-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@6'
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: test
          command: npm test
